# Generated by Django 3.2.13 on 2022-06-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Title',
            field=models.CharField(default='blog_post', max_length=200),
        ),
    ]
